spring:
  datasource:
    url: jdbc:mysql://lion-db.cx8gau8swil2.ap-northeast-2.rds.amazonaws.com:3306/mydatabase
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect